name: Deploy to Codeberg Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate interactive plot
        run: python main.py

      - name: Deploy to Codeberg Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CODEBERG_TOKEN }}
          publish_dir: .  # Publish the current directory

